[build-system]
requires = ["flit_core>=3,<4"]
build-backend = "flit_core.buildapi"

[project]
authors = [{ name = "Planetarium", email = "engineering@planetariumhq.com" }]
name = "app"
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "structlog ~=24.1.0",
    "fastapi ~=0.110.1",
    "uvicorn ~=0.29.0",
    "python-dotenv ~=1.0.1",
    "pydantic-settings ~=2.2.1",
]
dynamic = ["version", "description"]

[project.optional-dependencies]
test = [
    "pytest >=7.0,<7.2",
    "pytest-mock >=3.6.0,<3.10",
    "pytest-cov >=2.10.0,<3.0.0",
]
type = ["mypy ==0.971"]
dev = [
    "pre-commit >=2.17.0,<3.0.0",
    "colorama >=0.4.3,<0.5.0",
    "black ~=22.6.0",
    "isort >=5.0.6,<6.0.0",
]

[tool.flit.sdist]
include = ["app/*"]
exclude = [".env.sample", ".vscode/*", "tests/*", "scripts/*"]

[tool.flit.module]
name = "app"

[tool.black]
line-length = 88

[tool.pytest.ini_options]
addopts = "--cov=app"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
skip_gitignore = true
