name: Validate data

on:
  push:
    paths:
      - "data/mods/**"
      - "public/images/**"
      - "data/mod-tags.json"
  pull_request:

jobs:
  validate:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Files
        run: bash scripts/validate-data.sh
